version: "3"

services:
  git_builder:
    build: ./git-builder
    image: git-builder
    command:
      - https://github.com/react-boilerplate/react-boilerplate.git
    volumes:
      - src:/usr/src/app

  node_builder:
    build: ./node-builder
    image: node-builder
    command:
      - /bin/sh
      - -c
      - npm install && npm run test && npm run build
    volumes:
      - src:/usr/src/app

  docker_builder:
    build: ./docker-builder
    image: docker-builder
    environment:
      BUILD_TAG: react-boilerplate:latest
      DOCKERFILE: /dockerfiles/nginx.dockerfile
    volumes:
      - src:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock

  orchestrator:
    build: ./orchestrator
    image: orchestrator
    environment:
      BUILD_TAG: react-boilerplate
      DOCKERFILE: /dockerfiles/nginx.dockerfile
      GIT_URL: https://github.com/react-boilerplate/react-boilerplate.git
    volumes:
      - src:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock

  react_boilerplate:
    image: react-boilerplate
    ports:
      - 80:80

volumes:
  src:
